# Generated by Django 3.0.5 on 2020-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL',
            field=models.IntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Serum',
            field=models.IntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Total_chol',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
