# Generated by Django 3.0.5 on 2020-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200510_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Serum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Total_chol',
            field=models.IntegerField(blank=True),
        ),
    ]
