# Generated by Django 3.0.5 on 2020-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200510_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Serum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Total_chol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
