# Generated by Django 3.0.5 on 2020-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200510_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Serum',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Total_chol',
            field=models.FloatField(null=True),
        ),
    ]
