# Generated by Django 3.0.5 on 2020-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200510_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Serum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TGlob',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Talbo',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Total_chol',
            field=models.FloatField(null=True),
        ),
    ]
