# Generated by Django 3.0.5 on 2020-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200510_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Serum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Total_chol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
