# Generated by Django 3.0.5 on 2020-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200510_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='indir',
        ),
        migrations.AddField(
            model_name='patient',
            name='bilirubin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Bilirubin+Alkaline Phosphate'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='leftest',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Protien'),
        ),
    ]
