# Generated by Django 3.0.5 on 2020-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200510_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='directa',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='totka',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
