# Generated by Django 3.0.5 on 2020-05-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200510_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='TGlob',
        ),
    ]
