# Generated by Django 3.0.5 on 2020-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200510_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='St5',
            field=models.BooleanField(blank=True, default=False, verbose_name='Widal Test'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='St9',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
