# Generated by Django 3.0.5 on 2020-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_patient_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='AkPh',
            field=models.BooleanField(blank=True, default=False, verbose_name='Alkaline Phosphate'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bilirubin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Bilirubin'),
        ),
    ]
