# Generated by Django 3.0.5 on 2020-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200512_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='akg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
