# Generated by Django 3.0.5 on 2020-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_patient_akg'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Serum_Calcium',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Calcium'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Serum_Pottasium',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Pottasium'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Serum_Sodium',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Sodium'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Uric_Acid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Uric Acid'),
        ),
        migrations.AddField(
            model_name='patient',
            name='serumcrea',
            field=models.BooleanField(blank=True, default=False, verbose_name='Serum Creatinine'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='KFT',
            field=models.BooleanField(blank=True, default=False, verbose_name='Blood Urea'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
