# Generated by Django 3.0.5 on 2020-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200512_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sgot',
            new_name='sgotfield',
        ),
        migrations.AddField(
            model_name='patient',
            name='Sgot',
            field=models.BooleanField(blank=True, default=False, verbose_name='S.G.O.T '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sgpt',
            field=models.BooleanField(blank=True, default=False, verbose_name='S.G.P.T '),
        ),
    ]
